version: '3.4'

services:
  catalogdb:
    image: postgres:17.0

  basketdb:
    image: postgres:17.0

  distributedcache:
    image: redis:7.4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
