version: '3.4'

services:
  catalogdb:
    image: postgres:17.0

  basketdb:
    image: postgres:17.0

  distributedcache:
    image: redis:7.4

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-CU15-GDR1-ubuntu-22.04

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  mssql_order:  
