name: Docker Image CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions: 
  contents: read

jobs:
  docker-build-and-push:
    runs-on: ubuntu-24.04
    env:
      REF: ${{ github.head_ref || github.ref_name }}
    strategy:
      matrix:
        service:
            - { name: "Basket", context: "./src", dockerfile: "./src/Services/Basket/Basket.Api/Dockerfile", repository: "basket" }
            - { name: "Catalog", context: "./src", dockerfile: "./src/Services/Catalog/Catalog.API/Dockerfile", repository: "catalog" }
            - { name: "Discount", context: "./src", dockerfile: "./src/Services/Discount/Discount.Grpc/Dockerfile", repository: "discount" }
            - { name: "Ordering", context: "./src", dockerfile: "./src/Services/Ordering/Ordering.API/Dockerfile", repository: "ordering" }
            - { name: "YarpApiGateway", context: "./src", dockerfile: "./src/ApiGateways/YarpApiGateway/Dockerfile", repository: "yarpapigateway" }
            - { name: "WebApp", context: "./src", dockerfile: "./src/WebApps/Shopping.Web/Dockerfile", repository: "webapp" }
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Get current tag
      run: |
        echo "Tag name from REF: $REF"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  

    - name: Build and Push ${{ matrix.service.name }}
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        push: true
        tags: ${{ vars.ACR_URL }}/${{ vars.REPOSITORY }}-${{ matrix.service.repository }}:${{ env.REF }}
        labels: ${{ github.sha }}
        platforms: linux/amd64

    