# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  workflow_dispatch:
    inputs:
      buildConfiguration:
        description: 'Build configuration (e.g., Debug or Release)'
        required: true
        default: 'Release'
      dotnetVersion:
        description: 'Version of .NET SDK to use'
        required: true
        default: '8.0.x'
      solution:
        description: 'Path to solution.'
        required: true
        default: 'eshop-microservices.sln' # Adjust if needed

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ github.event.inputs.dotnetVersion }}

    - name: Restore dependencies
      run: dotnet restore ${{ github.event.inputs.solution }}
      working-directory: ./src  # Adjust this if the solution file is in ./src

    - name: Build
      run: dotnet build ${{ github.event.inputs.solution }} --configuration ${{ github.event.inputs.buildConfiguration }} --no-restore
      working-directory: ./src  # Adjust this if necessary

    - name: Test
      run: dotnet test ${{ github.event.inputs.solution }} --configuration ${{ github.event.inputs.buildConfiguration }} --no-build --verbosity normal
      working-directory: ./src  # Adjust this if necessary
