name: .NET with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    # Step 2: Set up .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ vars.SOLUTION_PATH }}

    # Step 4: Build the project
    - name: Build Project
      run: dotnet build ${{ vars.SOLUTION_PATH }} --configuration ${{ vars.DOTNET_CONFIGURATION }} --no-restore

    # Step 5: Run tests
    - name: Run Tests
      run: dotnet test ${{ vars.SOLUTION_PATH }} --configuration ${{ vars.DOTNET_CONFIGURATION }} --no-build --verbosity normal

    # Step 6: Set up Docker
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    # Step 7: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 8: Build and push Docker images using docker-compose
    - name: Build and push Docker images with Docker Compose
      run: |
        docker-compose -f src/docker-compose.yml build 
        docker-compose -f src/docker-compose.yml push
